### ISSUE TITLE
Write schema to file only on change

### ISSUE THREAD

**Issue by pristas-peter** [NickyMeuleman/gatsby-plugin-lint-queries#2]
Hi, you should write schema to file only if schema has changed to avoid unnecessary runs from other programs watching it.

**Comment by NickyMeuleman** [comment]
Hi from the future!
Sorry for neglecting this repo for such a long time.

Is this the same issue as #4 ?

I just released v0.1.0, it prints a .graphql file by default.
Maybe that file doesn't change between runs?

If it still changes, you can edit the generated schema via lifecycle hooks now.
