### ISSUE TITLE
Generate stable schema

### ISSUE THREAD

**Issue by jfrolich** [NickyMeuleman/gatsby-plugin-lint-queries#4]
Right now the schema is not stable, so everytime it runs a new schema is generated. This is an issue when you'd like to check it in in source control.

A solution would be to sort the arrays in the schema.

**Comment by jonny-harte** [comment]
Second! I tried ignoring it but it doesn't generate on build and fails CI

**Comment by jfrolich** [comment]
See my fork to have a stable schema: https://github.com/jfrolich/gatsby-plugin-extract-schema

**Comment by NickyMeuleman** [comment]
Thank you so much! I am so glad you fixed the issue by forking.
And sorry for not looking at this repository for a long while.

I just released `v0.1.0`, it prints a `.graphql` file by default.
Maybe that file doesn't change between runs?

If it still changes, you can edit the generated schema via a lifecycle hook now.
The docs describe how, your `sort` function would go in `adjustSchema`.
