### ISSUE TITLE
With Gatsby v3, introspectionQuery no longer exists within gatsby/graphql

### ISSUE THREAD

**Issue by dungle-scrubs** [NickyMeuleman/gatsby-plugin-lint-queries#5]
After updating to Gatsby v3, schema.json wasn't being created any longer.  After a little digging, it looks like `const { introspectionQuery, graphql } = require("gatsby/graphql");` is referencing a `string` that is no longer being exported from 'gatsby/graphql'.

Looking closer at `graphql.js`, `{ GraphQLJSON }` no longer contains `introspectionQuery` in the latest version of `graphql-compose`

**Comment by NickyMeuleman** [comment]
Hi! Thanks for pointing me in the right direction.

Changed the way the schema is fetched.
Version `0.1.0` is compatible with Gatsby v3 🎉

It write the schema in `.graphql` format by default now.
If you prefer to keep using `.json`, the docs should tell you how.

Let me know if this fixes your issue, if it doesn't I'll re-open this issue.
