### ISSUE TITLE
Support Gatsby 4

### ISSUE THREAD

**Issue by spikyjt** [NickyMeuleman/gatsby-plugin-lint-queries#9]
This could be as simple as updating `peerDependencies` to `"gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0".

I haven't tested extensively, but it seems to work fine on my sites after migration to v4, but there's a complaint from both npm and the gatsby build that this plugin doesn't support gatsby 4.

**Comment by NickyMeuleman** [comment]
If it is, great!
If not, I'll have a poke around in the Gatsby sourcecode to figure out what needs to change.

Want to give it a go and send a PR with that change?
